### ISSUE TITLE
CPDB Geospatial Check

### ISSUE THREAD

**Issue by td928** [NYCPlanning/data-engineering-qaqc#73]
Checking if admin boundaries are appropriately applied. One good way to check is spotting in the final admin boundary table whether they are appropriately populated and also whether those boundaries are stable over time e.g. a project that is assigned to one census tract is likely to stay in the same census tract in the next version. This might be comparable to outlier thinking in PLUTO.

[some past issue #90](https://github.com/NYCPlanning/db-cpdb/issues/90) would be good example where the field name or the admin boundary type is no longer available in the source data we used to do spatial join.

Another geospatial check aspect is whether all the projects are falling into the NYC five borough boundaries. All the projects that are outside the boundaries should be manually checked to confirm whether their location is true or not. In [this issue](https://github.com/NYCPlanning/db-cpdb/issues/106), the source data needed to be reprojected to be within the NYC boundaries.

**Comment by td928** [comment]
@AmandaDoyle on thoughts on this particular issue and scope of the improvement.

**Comment by AmandaDoyle** [comment]
@td928 and team - I think this is a good draft and I propose simplifying the first report you've outlined.  In summary here is what I propose in order of ease on implementing and impact on catching errors.
1) Check to see that all mapped capital projects fall within NYC.  This can be a simple ST Intersect check with the CPDB geometries and the NYC borough boundaries water included, and you'll report out the CPDB records that do not intersect the NYC borough boundaries water included.
2) This encompasses both the first and second QAQC check you've outlined and works to simplify it.  Report the following:
- The distinct list of admin boundary types in the admin boundary table between the current and previous CPDB version.  This will tell us if we're missing any admin boundaries from the table.
- Optional:
     - Report the number of projects and/or sum of planned commitments by community district and/or other admin boundary types between the current and previous CPDB version.  This will tell us if there are any anomalies in the distribution of projects across the city.
3) Show a map of all point and polygon geometries in the current CPDB.  This will allow someone to eyeball any egregiously wrong geometries (i.e. polygon that covers all of NYC or lines that are really harsh, like we saw in the "noodle" issue)

Each of these should be made into their own issue so that different team members can tackle them.
